Django-Bank/src/accounts/urls.py
from django.conf.urls import url


from .views import (
    login_view,
    register_view,
    logout_view
)

app_name = 'accounts'

urlpatterns = [
    url(r'^login/$', login_view, name='login'),
    url(r'^register/$', register_view, name='register'),
    url(r'^logout/$', logout_view, name='logout'),
]

Django-Bank/src/bankingsystem/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin

from core.views import home, about


urlpatterns = [
    # admin
    url(r'^admin/', admin.site.urls),
    # Accounts
    url(r'^accounts/', include('accounts.urls', namespace='accounts')),
    # core
    url(r'^$', home, name='home'),
    url(r'^about/$', about, name='about'),
    # transactions
    url(r'^', include('transactions.urls', namespace='transactions')),
]


if settings.DEBUG:
    urlpatterns += static(
        settings.STATIC_URL,
        document_root=settings.STATIC_ROOT
        )
    urlpatterns += static(
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT
        )

Django-Bank/src/transactions/urls.py
from django.conf.urls import url

from .views import deposit_view, withdrawal_view


app_name = 'transactions'

urlpatterns = [
    # url(r'^$', home_view, name='home'),
    url(r'^deposit/$', deposit_view, name='deposit'),
    url(r'^withdrawal/$', withdrawal_view, name='withdrawal'),
]

Django-Bank/src/accounts/models.py
from django.contrib.auth.models import AbstractUser
from django.core.validators import (
    MinValueValidator,
    MaxValueValidator,
    RegexValidator,
)
from django.db import models
from django.urls import reverse
from django.utils.translation import ugettext_lazy as _

from .managers import UserManager


class User(AbstractUser):
    username = models.CharField(
        _('username'), max_length=30, unique=True, null=True, blank=True,
        help_text=_(
            'Required. 30 characters or fewer. Letters, digits and '
            '@/./+/-/_ only.'
        ),
        validators=[
            RegexValidator(
                r'^[\w.@+-]+$',
                _('Enter a valid username. '
                    'This value may contain only letters, numbers '
                    'and @/./+/-/_ characters.'), 'invalid'),
        ],
        error_messages={
            'unique': _("un utilisateur avec ce pseudo existe déjà."),
        })

    email = models.EmailField(unique=True, null=False, blank=False)
    contact_no = models.IntegerField(unique=True, blank=True, null=True)
    matricule = models.IntegerField(unique=True, blank=True, null=True)
    grade = models.CharField(max_length=255, unique=True, null=True, blank=True)
    fonction = models.CharField(max_length=255, unique=True, null=True, blank=True)

    objects = UserManager()

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    def __str__(self):
        return self.email

    @property
    def account_no(self):
        if hasattr(self, 'account'):
            return self.account.account_no
        return None

    @property
    def full_name(self):
        return '{} {}'.format(self.first_name, self.last_name)

    @property
    def balance(self):
        if hasattr(self, 'account'):
            return self.account.balance
        return None

    @property
    def amount_arrete(self):
        if hasattr(self, 'account'):
            return self.account.amount_arrete
        return None

    @property
    def amount_percu(self):
        if hasattr(self, 'account'):
            return self.account.amount_percu
        return None

    @property
    def amount_restant(self):
        if hasattr(self, 'account'):
            return self.account.amount_restant
        return None

    @property
    def full_address(self):
        if hasattr(self, 'address'):
            return '{}, {}-{}, {}'.format(
                self.address.street_address,
                self.address.city,
                self.address.postal_code,
                self.address.country,
            )
        return None


class AccountDetails(models.Model):
    GENDER_CHOICE = (
        ("M", "Male"),
        ("F", "Female"),
    )
    user = models.OneToOneField(
        User,
        related_name='account',
        on_delete=models.CASCADE,
    )
    account_no = models.PositiveIntegerField(
        unique=True,
        validators=[
            MinValueValidator(10000000),
            MaxValueValidator(99999999)
        ]
    )
    gender = models.CharField(max_length=1, choices=GENDER_CHOICE)
    matricule = models.CharField(max_length=5)
    grade = models.CharField(max_length=255)
    fonction = models.CharField(max_length=255)
    # birth_date = models.DateField(null=True, blank=True)
    amount_arrete = models.DecimalField(
        default=0,
        max_digits=12,
        decimal_places=2
    )
    amount_percu = models.DecimalField(
        default=0,
        max_digits=12,
        decimal_places=2
    )
    # amount_restant = models.DecimalField(
    #     default=0,
    #     max_digits=12,
    #     decimal_places=2,
    # )
    balance = models.DecimalField(
        default=0,
        max_digits=12,
        decimal_places=2
    )
    picture = models.ImageField(
        null=True,
        blank=True,
        upload_to='account_pictures/',
    )

    def __str__(self):
        return str(self.account_no)

class UserAddress(models.Model):
    user = models.OneToOneField(
        User,
        related_name='address',
        on_delete=models.CASCADE,
    )
    street_address = models.CharField(max_length=512)
    city = models.CharField(max_length=256)
    postal_code = models.PositiveSmallIntegerField()
    country = models.CharField(max_length=256)

    def __str__(self):
        return self.user.username

Django-Bank/src/core/models.py
from django.db import models

# Create your models here.

Django-Bank/src/core/views.py
from django.db.models import Sum
# from django.db.models import Subtract
from django.shortcuts import render

from transactions.models import Deposit, Withdrawal, Interest

from django.db.models import F

# …

# deposit = deposit.annotate(
#     amount_restant=F('amount_arrete') - F('amount_percu')
# )


def home(request):
    if not request.user.is_authenticated:
        return render(request, "core/index.html", {})
    else:
        user = request.user
        deposit = Deposit.objects.filter(user=user)
        deposit_sum = deposit.aggregate(Sum('amount'))['amount__sum']
        # deposit_subtract = deposit.aggregate(Subtract('amount_arrete'))['amount__sub']
        deposit_arrete = deposit.aggregate(Sum('amount_arrete'))['amount_arrete__sum']
        deposit_rest = deposit.aggregate(Sum('amount_restant'))['amount_restant__sum']
        withdrawal = Withdrawal.objects.filter(user=user)
        withdrawal_sum = withdrawal.aggregate(Sum('amount'))['amount__sum']
        withdrawal = Withdrawal.objects.filter(user=user)
        withdrawal_rest =  withdrawal.aggregate(Sum('amount_restant'))['amount_restant__sum']
        interest = Interest.objects.filter(user=user)
        interest_sum = interest.aggregate(Sum('amount'))['amount__sum']

        context = {
                    "user": user,
                    "deposit": deposit,
                    "deposit_sum": deposit_sum,
                    "deposit_arrete": deposit_arrete,
                    "deposit_rest": deposit_rest,
                    "withdrawal": withdrawal,
                    "withdrawal_sum": withdrawal_sum,
                    "withdrawal_rest": withdrawal_rest,
                    "interest": interest,
                    "interest_sum": interest_sum,
                }

        return render(request, "core/transactions.html", context)


def about(request):
    return render(request, "core/about.html", {})

Django-Bank/src/core/templates/core/about.html
{% extends 'core/base.html' %}

{% block title %} À propos | {{ block.super }}{% endblock title %}

{% block content %}

<h1>A propos</h1>
<hr>
<p>LA CRÉANCE, QU’EST-CE QUE C’EST ?

Une créance Agent est une dette due par les agents à une entreprise. Les créances agents sont constituées de toutes les factures impayées à l’entreprise dont la date d’échéance est dépassée. Elles ne concernent donc pas les factures qui sont en attente de règlement. La situation inverse (les créances dues par l’entreprise à ses agents) s’appelle la dette.</p>

{% comment %} <p>It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for 'lorem ipsum' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like).
</p> {% endcomment %}


{% comment %} <p>The standard chunk of Lorem Ipsum used since the 1500s is reproduced below for those interested. Sections 1.10.32 and 1.10.33 from "de Finibus Bonorum et Malorum" by Cicero are also reproduced in their exact original form, accompanied by English versions from the 1914 translation by H. Rackham.</p> {% endcomment %}

{% endblock content %}

Django-Bank/src/core/templates/core/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head><link rel="shortcut icon" href="static/img/logo - Copie.png">
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <title>{% block title %} LMC,SA {% endblock title %}</title>

    <!-- Bootstrap -->
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
  </head>

  <body>
{% include "core/navbar.html" %}

<div class="container" style="padding-top: 60px;">
{% block content %}

{% endblock content %}
</div>
{% include "core/footer.html" %}

    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </body>
</html>

Django-Bank/src/core/templates/core/footer.html
<hr>
<footer class="footer navbar-fixed">
    <!--Footer Links-->
    <div class="container-fluid">
        <div class="row">
            <!--First column-->
            {% comment %} <div class="col-md-6">
                <h4 class="title"><b>Footer Content</b></h4>
                <p>Here you can use rows and columns here to organize your footer content.</p>
            </div> {% endcomment %}
            <!--/.First column-->
            <!--Second column-->
            {% comment %} <div class="col-md-6 text-center">
                <h5 class="title"><b>Links</b></h5>

                <a href="{% url 'home' %}">Accueil </a>|
                <a href="{% url 'about' %}">À propos</a> |&nbsp;


            </div> {% endcomment %}
            <!--/.Second column-->
        </div>
    </div>
    <!--/.Footer Links-->
    <!--Copyright-->
    <div class="footer-copyright">
        <div class="container-fluid">
            {% comment %} © 2017 Copyright: <a href="http://127.0.0.1:8000/"> </a> {% endcomment %}
            <p class="m-4 text-center"><b>Copyright&copy;2022</b> Cellule d'Etudes, Planifications et Informatique</p>
        </div>
    </div>
    <!--/.Copyright-->
</footer>
<br>

Django-Bank/src/core/templates/core/home.html
{% extends 'core/base.html' %}

{% block title %} {{ block.super }}{% endblock title %}

{% block content %}
<div class="container" style="padding-top: 50px;">
<div class="jumbotron text-center">
      <div class="container">
        <h1 class="jumbotron-heading">LMC,SA</h1>
        <hr>
        <p class="lead text-muted">Quelque chose de court et de principal sur la collection ci-dessous - son contenu, le créateur, etc. Faites-le court et doux, mais pas trop court pour que les gens ne le sautent pas complètement.</p>
        <p>
          <a class="btn btn-primary btn-md" href="{% url 'accounts:login' %}" role="button">Login</a>
          <a class="btn btn-success btn-md" href="{% url 'accounts:register' %}" role="button">Crée Compte Trésorie</a>
        </p>
      </div>
</div>
</div>

{% endblock content %}

Django-Bank/src/core/templates/core/index.html
{% load static %}
<!doctype html>
<html lang="en">
  {% comment %} <img src="static/img/logo - Copie.png" alt="..." height="30"> {% endcomment %}
  <head><link rel="shortcut icon" href="static/img/logo - Copie.png">
    <title>LMC, SA</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,700,800" rel="stylesheet">

    <link rel="stylesheet" href="{% static 'mycss/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'mycss/animate.css' %}">
    <link rel="stylesheet" href="{% static 'mycss/owl.carousel.min.css' %}">
    <link rel="stylesheet" href="{% static 'mycss/magnific-popup.css' %}">

    <!-- Theme Style -->
    <link rel="stylesheet" href="{% static 'mycss/style.css' %}">
  </head>
  <body>
    <header role="banner">
      <nav class="navbar navbar-expand-md navbar-dark bg-dark">
        <div class="container">
        <a class="navbar-brand" href="{% url 'home' %}">
        <img src="static/img/logo - Copie.png" alt="..." height="60">
        </a><a class="navbar-brand" href="{% url 'home' %}">Lignes Maritimes Congolaises</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExample05" aria-controls="navbarsExample05" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>

          <div class="collapse navbar-collapse" id="navbarsExample05">
            <ul class="navbar-nav ml-auto pl-lg-5 pl-0">
              <li class="nav-item">
                <a class="nav-link active" href="{% url 'home' %}">Accueil</a>
              </li>
              {% comment %} <li class="nav-item">
                <a class="nav-link" href="{% url 'transactions:deposit' %}">Deposit</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'transactions:withdrawal' %}">Withdraw</a>
              </li> {% endcomment %}
              <li class="nav-item">
                <a class="nav-link" href="{% url 'about' %}">A propos</a>
              </li>
            </ul>

            <ul class="navbar-nav ml-auto">
              <li class="nav-item cta-btn">
                <a class="nav-link" href="{% url 'accounts:register' %}">Crée Compte Trésorerie</a>
              </li>
            </ul>
            
          </div>
        </div>
      </nav>
    </header>
    <!-- END header -->
    
    <section class="home-slider owl-carousel">
      <div class="slider-item">
        <div class="container">
          <div class="row slider-text align-items-center justify-content-center">
            <div class="col-md-8 text-center col-sm-12 element-animate">
              <h1>GESTION DES CREANCES</h1>
              <p class="mb-5"><h3>CréanceApp</h3> est une plate-forme qui nous permet de gerer les créances des agents dues par l'Entreprise</p>
              <p><a href="{% url 'accounts:login' %}" class="btn btn-white btn-outline-success">Log In To Account</a></p>
            </div>
          </div>
        </div>

      </div>

        
      </div>

    </section>
    <script src="{% static 'myjs/jquery-3.2.1.min.js' %}"></script>
    <script src="{% static 'myjs/popper.min.js' %}"></script>
    <script src="{% static 'myjs/bootstrap.min.js' %}"></script>
    <script src="{% static 'myjs/owl.carousel.min.js' %}"></script>
    <script src="{% static 'myjs/jquery.waypoints.min.js' %}"></script>
    <script src="{% static 'myjs/jquery.magnific-popup.min.js' %}"></script>
    <script src="{% static 'myjs/magnific-popup-options.js' %}"></script>

    <script src="{% static 'myjs/main.js' %}"></script>
  </body>
</html>

Django-Bank/src/core/templates/core/messages.html
{% for message in messages %}
  <div class="alert {{ message.tags }} alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
    {{ message }}
  </div>
{% endfor %}

Django-Bank/src/core/templates/core/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-primary"">
  <a class="navbar-brand" href="{% url 'home' %}">
      <img src="static/img/logo - Copie.png" alt="..." height="40">
  </a><a class="navbar-brand" href="{% url 'home' %}">Lignes Maritimes Congolaises,sa</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'home' %}"><b>Accueil</b></a>
      </li>
      {% comment %} <li class="nav-item">
        <a class="nav-link" href="{% url 'transactions:deposit' %}">Deposit</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'transactions:withdrawal' %}">Withdraw</a>
      </li> {% endcomment %}
      <li class="nav-item">
        <a class="nav-link" href="{% url 'about' %}"><b>A propos</b></a>
      </li>
    </ul>
    <form class="form-inline my-2 my-lg-0">
        {% if request.user.is_authenticated %}
            <a href="{% url 'accounts:logout' %}" class="btn btn-danger btn-sm" type="button">Logout</a>
        {% else %}
            <a href="{% url 'accounts:login' %}" class="btn btn-success btn-sm" type="button">Login</a> |
            <a href="{% url 'accounts:register' %}" class="btn btn-primary btn-sm" type="button">Crée Compte Trésorerie</a>
        {% endif %}
    </form>
  </div>
</nav>

Django-Bank/src/core/templates/core/transactions.html
{% extends 'core/base.html' %}
{% block head_extra %}
<script type="text/javascript" src="https://cdn.jsdelivr.net/jquery/latest/jquery.min.js"></script>
<script type="text/javascript" src="https://cdn.jsdelivr.net/momentjs/latest/moment.min.js"></script>
<script type="text/javascript" src="https://cdn.jsdelivr.net/npm/daterangepicker/daterangepicker.min.js"></script>
{% comment %} <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
<div class="wrapper overflow"> {% endcomment %}
<link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/daterangepicker/daterangepicker.css" />

{% endblock %}

{% block title %} Transactions | {{ block.super }}{% endblock title %}

{% block content %}
{% include "core/messages.html" %}
{% load mathfilters %}
    <div class="page-header">
      <h1 class="text-center"><b>Lignes Maritimes Congolaises</b><br><small>Armement National</small></h1>
    </div>

<div class="row">

  <div class="col-xs-12 col-md-8 text-left">
    <h4><b>Nom du compte: </b>{{ user.full_name }}</h4>
    <h4><b>Date de Naissance: </b>{{ user.account.birth_date }}</h4>
    <h4><b>Genre: </b>{{ user.account.get_gender_display }}</h4>
    <h4><b>Téléphone: </b>{{ user.contact_no }}</h4>
    <h4><b>Adresse E-mail: </b>{{ user.email }}</h4>
    <h4><b>Adresse: </b>{{ user.full_address }}</h4>
  </div>
  <div class="col-xs-6 col-md-4 text-left">
    <h4><b>Compte Créé: </b>{{ user.date_joined|date:'d-m-Y' }}</h4>
    <h4><b>N° Compte Trésorerie: </b>{{ user.account_no }}</h4>
    <h4><b>Matricule: </b>{{user.account.matricule}}</h4>
    <h4><b>Grade: </b>{{user.account.grade}}</h4>
    <h4><b>Fonction: </b>{{user.account.fonction}}</h4></br></br>
    <div class="well">
    
    <h4 class="card"><b>Créance : {{ deposit_rest }},00 $</b></h4>
    {% comment %} <a class="btn btn-success" href="{% url 'transactions:deposit' %}">Deposit</a>
    <a class="btn btn-danger" href="{% url 'transactions:withdrawal' %}">Withdraw</a> {% endcomment %}
    </div>
  </div>

</div>

    {% comment %} <form method="get">
        <div class="mt-10 h-10 pl-3 pr-2 bg-white border rounded-md border-gray-500 flex justify-between items-center relative">
            <input type="search" name="daterange" id="search" placeholder="Filter using date range" value="{{ request.GET.daterange }}" class="appearance-none w-full outline-none focus:outline-none active:outline-none" />
            <button type="submit" class="ml-1 outline-none focus:outline-none active:outline-none">
                <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewBox="0 0 24 24" class="w-6 h-6">
                    <path d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z"></path>
                </svg>
            </button>
        </div>
        {% if form.daterange.errors %}
            {% for error in form.daterange.errors %}
                <p class="text-red-600 text-sm italic">{{ error }}</p>
            {% endfor %}
        {% endif %}
    </form> {% endcomment %}

<hr>

  <div class="page-header">
  <h2 class="text-center"><b>Détails de la Transaction</b></h2>
</div>
{% load mathfilters %}
<h3><b>Opérations</b></h3>
<table class="table table-hover table-bordered ">
  {% load mathfilters %}
  <thead>
    <tr>
      <th class="table-secondary text-center">N°</th>
      <th class="table-secondary text-center">DATE/HEURE</th>
      <th class="table-secondary text-center">LIBELLE</th>
      <th class="table-secondary text-center">REFERENCE</th>
      <th class="table-secondary text-center">MONTANTS ARRETES ($)</th>
      <th class="table-secondary text-center">MONTANTS PERCUS ($)</th>
      <th class="table-secondary text-center">MONTANTS RESTANTS ($)</th>
      {% comment %} <th class="table-secondary text-center">MONTANTS ($)</th> {% endcomment %}
      {% comment %} <th class="text-center">Montants ($)</th> {% endcomment %}
    </tr>
  </thead>
  <tbody>
    <tr>
    {% for obj in deposit %}
      <th class="text-center" scope="row">{{forloop.counter}}</th>
      {% load mathfilters %}
      <td class="text-center">{{ obj.timestamp }}</td>
      <td class="text-center">{{ obj.libelle }}</td>
      <td class="text-center">{{ obj.reference }}</td>
      <td class="text-center">{{ obj.amount_arrete }}</td>
      <td class="text-center">{{ obj.amount_percu }}</td>
      {% comment %} <td>{{ obj.calculate_balance }}</td> {% endcomment %}
      {% comment %} <td>{{ obj.amount_restant }}</td> {% endcomment %}
      {% comment %} <td>{{ obj.amount_arrete }} - {{ obj.amount_percu }}</td> {% endcomment %}
      {% comment %} <td>{{obj.amount_arrete |subtract: obj.amount_percu}}</td> {% endcomment %}
      <td class="text-center">{{ obj.amount_restant }}</td>
      {% comment %} <td>{{ obj.amount_arrete |sub: obj.amount_percu }}</td> {% endcomment %}
      {% comment %} <td class="text-center">{{ obj.amount }}</td> {% endcomment %}
    </tr>
    {% endfor %}
    <tr>
      <th class="text-center" scope="row" colspan="4">Total Général</th>
      <td class="text-center"><b>{{ deposit_arrete }},00 $</b></td>
      {% comment %} <th class="text-center" scope="row" colspan="4">Total Général</th>
      <td class="text-center">{{ deposit_sum }}</td> {% endcomment %}
      <th class="table-info text-center" scope="row" colspan="1">Montant Restant</th>
      <td class="table-info text-center"><b>{{ deposit_rest }},00 $</b></td>
      {% comment %} <td class="text-center"><b>{{ deposit_sum }}</b></td> {% endcomment %}
    </tr>
  </tbody>
</table>
<hr>

<h3><b>Détails Versement</b></h3>
<table class="table table-hover table-bordered">
  <thead>
    <tr>
      <th class="table-secondary text-center">N°</th>
      <th class="table-secondary text-center">DATE/HEURE</th>
      <th class="table-secondary text-center">LIBELLE</th>
      <th class="table-secondary text-center">REFERENCE</th>
      {% comment %} <th class="table-secondary text-center">MONTANT ($) DISPONIBLE</th> {% endcomment %}
      <th class="table-secondary text-center">MONTANT ($) </th>
    </tr>
  </thead>
  <tbody>
    <tr>
    {% for obj in withdrawal %}
      <th class="text-center" scope="row">{{forloop.counter}}</th>
      <td>{{ obj.timestamp }}</td>
      <td class="text-center">{{ obj.libelle }}</td>
      <td class="text-center">{{ obj.reference }}</td>
      {% comment %} <td class="text-center">{{ obj.amount }}</td> {% endcomment %}
      <td class="text-center">{{ obj.amount_restant }}</td>
    </tr>
    {% endfor %}
    <tr>
      {% comment %} <th class="text-center" scope="row" colspan="1">Total</th>
      <td class="table-info text-center"><b>{{ withdrawal_sum }},00 $</b></td> {% endcomment %}
            <th class="text-center" scope="row" colspan="4">Total</th>
      <td class="table-info text-center"><b>{{ withdrawal_rest }},00 $</b></td>
    </tr>
  </tbody>
</table>
<hr>


{% comment %} <h3>Interest Details</h3>
<table class="table table-hover table-bordered">
  <thead>
    <tr>
      <th>#</th>
      <th>Date / Time</th>
      <th>Details</th>
      <th>Amount ($)</th>
    </tr>
  </thead>
  <tbody>
    <tr>
    {% for obj in interest %}
      <th scope="row">{{forloop.counter}}</th>
      <td>{{ obj.timestamp }}</td>
      <td>Interest</td>
      <td>{{ obj.amount }}</td>
    </tr>
    {% endfor %}
    <tr>
      <th class="text-right" scope="row" colspan="3">Total</th>

      <td>{{ interest_sum }}</td>
    </tr>
   
  </tbody>
</table>
<hr> {% endcomment %}

{% endblock content %}

{% block footer_extra %}
    <script type="text/javascript">
        $(function () {
            $('input[name="daterange"]').daterangepicker({
                autoUpdateInput: false,
                locale: {
                    cancelLabel: "Clear",
                },
            });

            $('input[name="daterange"]').on("apply.daterangepicker", function (ev, picker) {
                $(this).val(picker.startDate.format("YYYY-MM-DD") + " - " + picker.endDate.format("YYYY-MM-DD"));
            });

            $('input[name="daterange"]').on("cancel.daterangepicker", function (ev, picker) {
                $(this).val("");
            });
        });
    </script>
{% endblock %}